steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud compute ssh himanshu@instance-20251025-043319 \
          --project=citric-celerity-416705 \
          --zone=us-central1-c \
          --command="mkdir -p /home/himanshu/linkedin-bot && \
            cd /home/himanshu/linkedin-bot && \
            git pull origin main && \
            source venv/bin/activate && \
            pip install -r requirements.txt && \
            sudo systemctl restart myapp.service || sudo systemctl start myapp.service"
options:
  logging: CLOUD_LOGGING_ONLY

