steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud compute ssh himanshu@instance-20251025-043319 \
          --project=citric-celerity-416705 \
          --zone=us-central1-c \
          --command="cd /home/himanshu/linkedin-bot && \
            git pull origin main && \
            source venv/bin/activate && \
            pip install -r requirements.txt && \
            nohup python3 cli.py start > server.log 2>&1 &"
options:
  logging: CLOUD_LOGGING_ONLY
