# cloudbuild.yaml
# Automatically deploys your Python app to GCE when you push code.

steps:
  # STEP 1: Print build info
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "=== Starting Cloud Build Deployment ==="
        echo "Git Commit: $COMMIT_SHA"
        echo "Branch: $BRANCH_NAME"
        echo "Project: citric-celerity-416705"
        echo "======================================="

  # STEP 2: SSH into VM and pull latest code + restart service
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        echo "=== Connecting to GCE instance and deploying ==="

        gcloud compute ssh instance-20251025-043319 \
          --project=citric-celerity-416705 \
          --zone=us-central1-c \
          --command="sudo bash -c '
            echo \"=== Stopping linkedin-bot service ===\" && \
            systemctl stop linkedin-bot && \
            echo \"=== Pulling latest code ===\" && \
            cd /home/himanshu/linkedin-bot && \
            git config --global --add safe.directory /home/himanshu/linkedin-bot && \
            git fetch origin && \
            git reset --hard origin/main && \
            echo \"=== Installing/Updating Python dependencies ===\" && \
            sudo -u himanshu python3 -m pip install --user -r requirements.txt --upgrade && \
            echo \"=== Reloading systemd and starting linkedin-bot service ===\" && \
            systemctl daemon-reload && \
            systemctl start linkedin-bot && \
            sleep 5 && \
            echo \"=== Checking service status ===\" && \
            systemctl status linkedin-bot --no-pager && \
            echo \"=== Deployment complete ===\"
          '"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
