steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud compute ssh himanshu@instance-20251025-043319 \
        --project=citric-celerity-416705 \
        --zone=us-central1-c \
        --command="cd /home/himanshu/linkedin-bot && \
        source venv/bin/activate && \
        pkill -f 'python3 cli.py start' || true && \
        nohup python3 cli.py start > server.log 2>&1 &"

options:
  logging: CLOUD_LOGGING_ONLY
